.pragma library

// Generated from package/translate/*/LC_MESSAGES/plasma_applet_pp.ua.xxanqw.justweather.po.
// Run tools/update-translations.sh after editing a PO file. Do not edit this file.

var catalogs = {
    "uk": {
        "General": [
            "Загальні"
        ],
        "Compact View": [
            "Компактний вигляд"
        ],
        "Desktop View": [
            "Вигляд на стільниці"
        ],
        "Forecast": [
            "Прогноз"
        ],
        "Icon style:": [
            "Стиль піктограм:"
        ],
        "Fill": [
            "Заповнені"
        ],
        "Line": [
            "Контурні"
        ],
        "Choose between filled or line icons": [
            "Оберіть заповнені або контурні піктограми"
        ],
        "Icon size (compact):": [
            "Розмір піктограми (компактний):"
        ],
        "%1 px": [
            "%1 пкс"
        ],
        "Icon size in compact/panel mode": [
            "Розмір піктограми в компактному режимі або на панелі"
        ],
        "Show icon in compact mode": [
            "Показувати піктограму в компактному режимі"
        ],
        "Display weather icon when widget is in panel": [
            "Показувати піктограму погоди, коли віджет розміщено на панелі"
        ],
        "Temperature value:": [
            "Значення температури:"
        ],
        "Actual": [
            "Фактична"
        ],
        "Feels like": [
            "Відчувається як"
        ],
        "Choose which temperature is shown in compact mode": [
            "Оберіть температуру для компактного режиму"
        ],
        "Font size (compact):": [
            "Розмір шрифту (компактний):"
        ],
        "%1 pt": [
            "%1 пт"
        ],
        "Temperature text size in compact/panel mode": [
            "Розмір тексту температури в компактному режимі або на панелі"
        ],
        "Show temperature in compact mode": [
            "Показувати температуру в компактному режимі"
        ],
        "Display temperature when widget is in panel": [
            "Показувати температуру, коли віджет розміщено на панелі"
        ],
        "Use bold font": [
            "Використовувати жирний шрифт"
        ],
        "Make temperature text bold": [
            "Показувати температуру жирним шрифтом"
        ],
        "Preview:": [
            "Попередній перегляд:"
        ],
        "Compact mode preview:": [
            "Попередній перегляд компактного режиму:"
        ],
        "Hourly forecast:": [
            "Погодинний прогноз:"
        ],
        "Show weather changes during the day": [
            "Показувати зміни погоди протягом дня"
        ],
        "Forecast horizon:": [
            "Горизонт прогнозу:"
        ],
        "%1 hour": [
            "%1 година",
            "%1 години",
            "%1 годин"
        ],
        "Display interval:": [
            "Інтервал показу:"
        ],
        "Every %1 hour": [
            "Щогодини",
            "Кожні %1 години",
            "Кожні %1 годин"
        ],
        "Temperature:": [
            "Температура:"
        ],
        "Show condition icons": [
            "Показувати піктограми стану погоди"
        ],
        "Show precipitation probability": [
            "Показувати ймовірність опадів"
        ],
        "Daily forecast:": [
            "Прогноз за днями:"
        ],
        "Show multi-day forecast": [
            "Показувати прогноз на кілька днів"
        ],
        "Number of days:": [
            "Кількість днів:"
        ],
        "Include today": [
            "Включати сьогодні"
        ],
        "Temperature range:": [
            "Діапазон температур:"
        ],
        "Forecast sections appear only in the expanded and desktop views. They are disabled by default to preserve the minimal layout. Forecast data provided by Open-Meteo.": [
            "Розділи прогнозу з’являються лише в розгорнутому вигляді та на стільниці. Типово їх вимкнено, щоб зберегти мінімалістичний вигляд. Дані прогнозу надає Open-Meteo."
        ],
        "Desktop Widget View:": [
            "Вигляд віджета на стільниці:"
        ],
        "Configure the appearance when widget is on desktop": [
            "Налаштуйте вигляд віджета на стільниці"
        ],
        "Icon size:": [
            "Розмір піктограми:"
        ],
        "Weather icon size in desktop mode": [
            "Розмір піктограми погоди в режимі стільниці"
        ],
        "Show weather icon": [
            "Показувати піктограму погоди"
        ],
        "Display weather icon in desktop widget": [
            "Показувати піктограму погоди у віджеті на стільниці"
        ],
        "Temperature size:": [
            "Розмір температури:"
        ],
        "Temperature text size in desktop mode": [
            "Розмір тексту температури в режимі стільниці"
        ],
        "Show temperature": [
            "Показувати температуру"
        ],
        "Display temperature in desktop widget": [
            "Показувати температуру у віджеті на стільниці"
        ],
        "Bold temperature text": [
            "Жирний текст температури"
        ],
        "Weather condition size:": [
            "Розмір опису погоди:"
        ],
        "Weather condition text size (e.g., 'Partly cloudy')": [
            "Розмір тексту опису погоди (наприклад, «Мінлива хмарність»)"
        ],
        "Show weather condition": [
            "Показувати опис погоди"
        ],
        "Display weather condition description": [
            "Показувати опис стану погоди"
        ],
        "These settings apply to the desktop widget view only. For panel/compact view, use the 'Compact View' tab.": [
            "Ці налаштування стосуються лише віджета на стільниці. Для панелі або компактного вигляду скористайтеся вкладкою «Компактний вигляд»."
        ],
        "System": [
            "Системна"
        ],
        "Language:": [
            "Мова:"
        ],
        "Location:": [
            "Розташування:"
        ],
        "Detect automatically": [
            "Визначати автоматично"
        ],
        "Use wttr.in IP-based location detection": [
            "Визначати розташування за IP-адресою через wttr.in"
        ],
        "Manual location:": [
            "Розташування вручну:"
        ],
        "City name, ZIP code, or coordinates": [
            "Назва міста, поштовий індекс або координати"
        ],
        "Enter city name (e.g., 'London'), ZIP code (e.g., '10001'), or coordinates (e.g., '51.5074,-0.1278')": [
            "Введіть назву міста (наприклад, «Лондон»), поштовий індекс (наприклад, «10001») або координати (наприклад, «51.5074,-0.1278»)"
        ],
        "Temperature unit:": [
            "Одиниця температури:"
        ],
        "Choose between Celsius and Fahrenheit": [
            "Оберіть градуси Цельсія або Фаренгейта"
        ],
        "Update interval (minutes):": [
            "Інтервал оновлення (хвилини):"
        ],
        "How often to refresh weather data (5-120 minutes)": [
            "Як часто оновлювати дані погоди (5–120 хвилин)"
        ],
        "Display:": [
            "Відображення:"
        ],
        "Show widget background": [
            "Показувати тло віджета"
        ],
        "Show/hide the widget background panel": [
            "Показати або приховати панель тла віджета"
        ],
        "Use compact mode": [
            "Використовувати компактний режим"
        ],
        "Use compact view as default (recommended for panel)": [
            "Типово використовувати компактний вигляд (рекомендовано для панелі)"
        ],
        "Weather data provided by wttr.in": [
            "Дані погоди надає wttr.in"
        ],
        "%1 · %2%": [
            "%1 · %2%"
        ],
        "Updating...": [
            "Оновлення…"
        ],
        "Feels like %1": [
            "Відчувається як %1"
        ],
        "H %1 / L %2": [
            "Макс. %1 / Мін. %2"
        ],
        "Update failed · Last update: %1": [
            "Не вдалося оновити · Останнє оновлення: %1"
        ],
        "Update failed": [
            "Не вдалося оновити"
        ],
        "Last update: %1": [
            "Останнє оновлення: %1"
        ],
        "Weather": [
            "Погода"
        ],
        "Current location": [
            "Поточне розташування"
        ],
        "No location set": [
            "Розташування не вказано"
        ],
        "Refresh weather": [
            "Оновити погоду"
        ],
        "Next %1 hour": [
            "Наступна %1 година",
            "Наступні %1 години",
            "Наступні %1 годин"
        ],
        "%1%": [
            "%1%"
        ],
        "Forecast unavailable": [
            "Прогноз недоступний"
        ],
        "Loading forecast...": [
            "Завантаження прогнозу…"
        ],
        "%1-day forecast": [
            "Прогноз на %1 дн."
        ],
        "%1° / %2°": [
            "%1° / %2°"
        ],
        "Today": [
            "Сьогодні"
        ],
        "Rain": [
            "Дощ"
        ],
        "Snow": [
            "Сніг"
        ],
        "Thunder": [
            "Гроза"
        ]
    },
    "zh_CN": {
        "General": [
            "常规"
        ],
        "Compact View": [
            "紧凑视图"
        ],
        "Desktop View": [
            "桌面视图"
        ],
        "Forecast": [
            "预报"
        ],
        "Icon style:": [
            "图标样式："
        ],
        "Fill": [
            "填充"
        ],
        "Line": [
            "线框"
        ],
        "Choose between filled or line icons": [
            "选择填充或线框图标"
        ],
        "Icon size (compact):": [
            "图标大小（紧凑）："
        ],
        "%1 px": [
            "%1 像素"
        ],
        "Icon size in compact/panel mode": [
            "紧凑或面板模式下的图标大小"
        ],
        "Show icon in compact mode": [
            "在紧凑模式下显示图标"
        ],
        "Display weather icon when widget is in panel": [
            "小部件位于面板时显示天气图标"
        ],
        "Temperature value:": [
            "温度值："
        ],
        "Actual": [
            "实际温度"
        ],
        "Feels like": [
            "体感温度"
        ],
        "Choose which temperature is shown in compact mode": [
            "选择紧凑模式下显示的温度"
        ],
        "Font size (compact):": [
            "字体大小（紧凑）："
        ],
        "%1 pt": [
            "%1 磅"
        ],
        "Temperature text size in compact/panel mode": [
            "紧凑或面板模式下的温度文字大小"
        ],
        "Show temperature in compact mode": [
            "在紧凑模式下显示温度"
        ],
        "Display temperature when widget is in panel": [
            "小部件位于面板时显示温度"
        ],
        "Use bold font": [
            "使用粗体"
        ],
        "Make temperature text bold": [
            "以粗体显示温度"
        ],
        "Preview:": [
            "预览："
        ],
        "Compact mode preview:": [
            "紧凑模式预览："
        ],
        "Hourly forecast:": [
            "逐小时预报："
        ],
        "Show weather changes during the day": [
            "显示一天内的天气变化"
        ],
        "Forecast horizon:": [
            "预报时长："
        ],
        "%1 hour": [
            "%1 小时"
        ],
        "Display interval:": [
            "显示间隔："
        ],
        "Every %1 hour": [
            "每 %1 小时"
        ],
        "Temperature:": [
            "温度："
        ],
        "Show condition icons": [
            "显示天气状况图标"
        ],
        "Show precipitation probability": [
            "显示降水概率"
        ],
        "Daily forecast:": [
            "每日预报："
        ],
        "Show multi-day forecast": [
            "显示多日预报"
        ],
        "Number of days:": [
            "天数："
        ],
        "Include today": [
            "包括今天"
        ],
        "Temperature range:": [
            "温度范围："
        ],
        "Forecast sections appear only in the expanded and desktop views. They are disabled by default to preserve the minimal layout. Forecast data provided by Open-Meteo.": [
            "预报区域仅显示在展开视图和桌面视图中。为保持简洁布局，默认关闭。预报数据由 Open-Meteo 提供。"
        ],
        "Desktop Widget View:": [
            "桌面小部件视图："
        ],
        "Configure the appearance when widget is on desktop": [
            "配置小部件位于桌面时的外观"
        ],
        "Icon size:": [
            "图标大小："
        ],
        "Weather icon size in desktop mode": [
            "桌面模式下的天气图标大小"
        ],
        "Show weather icon": [
            "显示天气图标"
        ],
        "Display weather icon in desktop widget": [
            "在桌面小部件中显示天气图标"
        ],
        "Temperature size:": [
            "温度大小："
        ],
        "Temperature text size in desktop mode": [
            "桌面模式下的温度文字大小"
        ],
        "Show temperature": [
            "显示温度"
        ],
        "Display temperature in desktop widget": [
            "在桌面小部件中显示温度"
        ],
        "Bold temperature text": [
            "温度使用粗体"
        ],
        "Weather condition size:": [
            "天气状况文字大小："
        ],
        "Weather condition text size (e.g., 'Partly cloudy')": [
            "天气状况文字大小（例如“局部多云”）"
        ],
        "Show weather condition": [
            "显示天气状况"
        ],
        "Display weather condition description": [
            "显示天气状况描述"
        ],
        "These settings apply to the desktop widget view only. For panel/compact view, use the 'Compact View' tab.": [
            "这些设置仅适用于桌面小部件视图。面板或紧凑视图请使用“紧凑视图”标签页。"
        ],
        "System": [
            "系统"
        ],
        "Language:": [
            "语言："
        ],
        "Location:": [
            "位置："
        ],
        "Detect automatically": [
            "自动检测"
        ],
        "Use wttr.in IP-based location detection": [
            "使用 wttr.in 根据 IP 检测位置"
        ],
        "Manual location:": [
            "手动位置："
        ],
        "City name, ZIP code, or coordinates": [
            "城市名称、邮政编码或坐标"
        ],
        "Enter city name (e.g., 'London'), ZIP code (e.g., '10001'), or coordinates (e.g., '51.5074,-0.1278')": [
            "输入城市名称（例如“伦敦”）、邮政编码（例如“10001”）或坐标（例如“51.5074,-0.1278”）"
        ],
        "Temperature unit:": [
            "温度单位："
        ],
        "Choose between Celsius and Fahrenheit": [
            "选择摄氏度或华氏度"
        ],
        "Update interval (minutes):": [
            "更新间隔（分钟）："
        ],
        "How often to refresh weather data (5-120 minutes)": [
            "天气数据刷新频率（5–120 分钟）"
        ],
        "Display:": [
            "显示："
        ],
        "Show widget background": [
            "显示小部件背景"
        ],
        "Show/hide the widget background panel": [
            "显示或隐藏小部件背景面板"
        ],
        "Use compact mode": [
            "使用紧凑模式"
        ],
        "Use compact view as default (recommended for panel)": [
            "默认使用紧凑视图（建议用于面板）"
        ],
        "Weather data provided by wttr.in": [
            "天气数据由 wttr.in 提供"
        ],
        "%1 · %2%": [
            "%1 · %2%"
        ],
        "Updating...": [
            "正在更新…"
        ],
        "Feels like %1": [
            "体感 %1"
        ],
        "H %1 / L %2": [
            "最高 %1 / 最低 %2"
        ],
        "Update failed · Last update: %1": [
            "更新失败 · 上次更新：%1"
        ],
        "Update failed": [
            "更新失败"
        ],
        "Last update: %1": [
            "上次更新：%1"
        ],
        "Weather": [
            "天气"
        ],
        "Current location": [
            "当前位置"
        ],
        "No location set": [
            "未设置位置"
        ],
        "Refresh weather": [
            "刷新天气"
        ],
        "Next %1 hour": [
            "未来 %1 小时"
        ],
        "%1%": [
            "%1%"
        ],
        "Forecast unavailable": [
            "预报不可用"
        ],
        "Loading forecast...": [
            "正在加载预报…"
        ],
        "%1-day forecast": [
            "%1 天预报"
        ],
        "%1° / %2°": [
            "%1° / %2°"
        ],
        "Today": [
            "今天"
        ],
        "Rain": [
            "降雨"
        ],
        "Snow": [
            "降雪"
        ],
        "Thunder": [
            "雷暴"
        ]
    },
    "ar": {
        "General": [
            "عام"
        ],
        "Compact View": [
            "العرض المدمج"
        ],
        "Desktop View": [
            "عرض سطح المكتب"
        ],
        "Forecast": [
            "التوقعات"
        ],
        "Icon style:": [
            "نمط الأيقونات:"
        ],
        "Fill": [
            "ممتلئة"
        ],
        "Line": [
            "خطية"
        ],
        "Choose between filled or line icons": [
            "اختر بين الأيقونات الممتلئة والخطية"
        ],
        "Icon size (compact):": [
            "حجم الأيقونة (مدمج):"
        ],
        "%1 px": [
            "%1 بكسل"
        ],
        "Icon size in compact/panel mode": [
            "حجم الأيقونة في الوضع المدمج أو اللوحة"
        ],
        "Show icon in compact mode": [
            "إظهار الأيقونة في الوضع المدمج"
        ],
        "Display weather icon when widget is in panel": [
            "إظهار أيقونة الطقس عند وضع الأداة في اللوحة"
        ],
        "Temperature value:": [
            "قيمة درجة الحرارة:"
        ],
        "Actual": [
            "الفعلية"
        ],
        "Feels like": [
            "المحسوسة"
        ],
        "Choose which temperature is shown in compact mode": [
            "اختر درجة الحرارة المعروضة في الوضع المدمج"
        ],
        "Font size (compact):": [
            "حجم الخط (مدمج):"
        ],
        "%1 pt": [
            "%1 نقطة"
        ],
        "Temperature text size in compact/panel mode": [
            "حجم نص درجة الحرارة في الوضع المدمج أو اللوحة"
        ],
        "Show temperature in compact mode": [
            "إظهار درجة الحرارة في الوضع المدمج"
        ],
        "Display temperature when widget is in panel": [
            "إظهار درجة الحرارة عند وضع الأداة في اللوحة"
        ],
        "Use bold font": [
            "استخدام خط عريض"
        ],
        "Make temperature text bold": [
            "عرض درجة الحرارة بخط عريض"
        ],
        "Preview:": [
            "معاينة:"
        ],
        "Compact mode preview:": [
            "معاينة الوضع المدمج:"
        ],
        "Hourly forecast:": [
            "التوقعات لكل ساعة:"
        ],
        "Show weather changes during the day": [
            "إظهار تغيرات الطقس خلال اليوم"
        ],
        "Forecast horizon:": [
            "مدة التوقعات:"
        ],
        "%1 hour": [
            "لا ساعات",
            "ساعة واحدة",
            "ساعتان",
            "%1 ساعات",
            "%1 ساعة",
            "%1 ساعة"
        ],
        "Display interval:": [
            "فاصل العرض:"
        ],
        "Every %1 hour": [
            "كل ساعة",
            "كل ساعة",
            "كل ساعتين",
            "كل %1 ساعات",
            "كل %1 ساعة",
            "كل %1 ساعة"
        ],
        "Temperature:": [
            "درجة الحرارة:"
        ],
        "Show condition icons": [
            "إظهار أيقونات حالة الطقس"
        ],
        "Show precipitation probability": [
            "إظهار احتمال الهطول"
        ],
        "Daily forecast:": [
            "التوقعات اليومية:"
        ],
        "Show multi-day forecast": [
            "إظهار توقعات عدة أيام"
        ],
        "Number of days:": [
            "عدد الأيام:"
        ],
        "Include today": [
            "تضمين اليوم"
        ],
        "Temperature range:": [
            "نطاق درجة الحرارة:"
        ],
        "Forecast sections appear only in the expanded and desktop views. They are disabled by default to preserve the minimal layout. Forecast data provided by Open-Meteo.": [
            "تظهر أقسام التوقعات فقط في العرض الموسع وعرض سطح المكتب. وهي معطلة افتراضيًا للحفاظ على التصميم البسيط. بيانات التوقعات مقدمة من Open-Meteo."
        ],
        "Desktop Widget View:": [
            "عرض أداة سطح المكتب:"
        ],
        "Configure the appearance when widget is on desktop": [
            "اضبط مظهر الأداة على سطح المكتب"
        ],
        "Icon size:": [
            "حجم الأيقونة:"
        ],
        "Weather icon size in desktop mode": [
            "حجم أيقونة الطقس في وضع سطح المكتب"
        ],
        "Show weather icon": [
            "إظهار أيقونة الطقس"
        ],
        "Display weather icon in desktop widget": [
            "إظهار أيقونة الطقس في أداة سطح المكتب"
        ],
        "Temperature size:": [
            "حجم درجة الحرارة:"
        ],
        "Temperature text size in desktop mode": [
            "حجم نص درجة الحرارة في وضع سطح المكتب"
        ],
        "Show temperature": [
            "إظهار درجة الحرارة"
        ],
        "Display temperature in desktop widget": [
            "إظهار درجة الحرارة في أداة سطح المكتب"
        ],
        "Bold temperature text": [
            "نص درجة الحرارة عريض"
        ],
        "Weather condition size:": [
            "حجم وصف الطقس:"
        ],
        "Weather condition text size (e.g., 'Partly cloudy')": [
            "حجم نص وصف الطقس (مثل «غائم جزئيًا»)"
        ],
        "Show weather condition": [
            "إظهار حالة الطقس"
        ],
        "Display weather condition description": [
            "إظهار وصف حالة الطقس"
        ],
        "These settings apply to the desktop widget view only. For panel/compact view, use the 'Compact View' tab.": [
            "تنطبق هذه الإعدادات على عرض أداة سطح المكتب فقط. لعرض اللوحة أو العرض المدمج، استخدم علامة تبويب «العرض المدمج»."
        ],
        "System": [
            "النظام"
        ],
        "Language:": [
            "اللغة:"
        ],
        "Location:": [
            "الموقع:"
        ],
        "Detect automatically": [
            "الكشف تلقائيًا"
        ],
        "Use wttr.in IP-based location detection": [
            "استخدام wttr.in لتحديد الموقع اعتمادًا على عنوان IP"
        ],
        "Manual location:": [
            "الموقع اليدوي:"
        ],
        "City name, ZIP code, or coordinates": [
            "اسم المدينة أو الرمز البريدي أو الإحداثيات"
        ],
        "Enter city name (e.g., 'London'), ZIP code (e.g., '10001'), or coordinates (e.g., '51.5074,-0.1278')": [
            "أدخل اسم المدينة (مثل «لندن») أو الرمز البريدي (مثل «10001») أو الإحداثيات (مثل «51.5074,-0.1278»)"
        ],
        "Temperature unit:": [
            "وحدة درجة الحرارة:"
        ],
        "Choose between Celsius and Fahrenheit": [
            "اختر بين الدرجة المئوية والفهرنهايت"
        ],
        "Update interval (minutes):": [
            "فاصل التحديث (بالدقائق):"
        ],
        "How often to refresh weather data (5-120 minutes)": [
            "معدل تحديث بيانات الطقس (5–120 دقيقة)"
        ],
        "Display:": [
            "العرض:"
        ],
        "Show widget background": [
            "إظهار خلفية الأداة"
        ],
        "Show/hide the widget background panel": [
            "إظهار أو إخفاء لوحة خلفية الأداة"
        ],
        "Use compact mode": [
            "استخدام الوضع المدمج"
        ],
        "Use compact view as default (recommended for panel)": [
            "استخدام العرض المدمج افتراضيًا (موصى به للوحة)"
        ],
        "Weather data provided by wttr.in": [
            "بيانات الطقس مقدمة من wttr.in"
        ],
        "%1 · %2%": [
            "%1 · %2%"
        ],
        "Updating...": [
            "جارٍ التحديث…"
        ],
        "Feels like %1": [
            "المحسوسة %1"
        ],
        "H %1 / L %2": [
            "العظمى %1 / الصغرى %2"
        ],
        "Update failed · Last update: %1": [
            "فشل التحديث · آخر تحديث: %1"
        ],
        "Update failed": [
            "فشل التحديث"
        ],
        "Last update: %1": [
            "آخر تحديث: %1"
        ],
        "Weather": [
            "الطقس"
        ],
        "Current location": [
            "الموقع الحالي"
        ],
        "No location set": [
            "لم يتم تحديد موقع"
        ],
        "Refresh weather": [
            "تحديث الطقس"
        ],
        "Next %1 hour": [
            "الآن",
            "الساعة القادمة",
            "الساعتان القادمتان",
            "%1 ساعات قادمة",
            "%1 ساعة قادمة",
            "%1 ساعة قادمة"
        ],
        "%1%": [
            "%1%"
        ],
        "Forecast unavailable": [
            "التوقعات غير متاحة"
        ],
        "Loading forecast...": [
            "جارٍ تحميل التوقعات…"
        ],
        "%1-day forecast": [
            "توقعات %1 أيام"
        ],
        "%1° / %2°": [
            "%1° / %2°"
        ],
        "Today": [
            "اليوم"
        ],
        "Rain": [
            "مطر"
        ],
        "Snow": [
            "ثلج"
        ],
        "Thunder": [
            "عواصف رعدية"
        ]
    },
    "fr": {
        "General": [
            "Général"
        ],
        "Compact View": [
            "Vue compacte"
        ],
        "Desktop View": [
            "Vue du bureau"
        ],
        "Forecast": [
            "Prévisions"
        ],
        "Icon style:": [
            "Style des icônes :"
        ],
        "Fill": [
            "Plein"
        ],
        "Line": [
            "Contour"
        ],
        "Choose between filled or line icons": [
            "Choisir des icônes pleines ou en contour"
        ],
        "Icon size (compact):": [
            "Taille de l’icône (compacte) :"
        ],
        "%1 px": [
            "%1 px"
        ],
        "Icon size in compact/panel mode": [
            "Taille de l’icône en mode compact ou panneau"
        ],
        "Show icon in compact mode": [
            "Afficher l’icône en mode compact"
        ],
        "Display weather icon when widget is in panel": [
            "Afficher l’icône météo lorsque le composant est dans le panneau"
        ],
        "Temperature value:": [
            "Valeur de température :"
        ],
        "Actual": [
            "Réelle"
        ],
        "Feels like": [
            "Ressentie"
        ],
        "Choose which temperature is shown in compact mode": [
            "Choisir la température affichée en mode compact"
        ],
        "Font size (compact):": [
            "Taille de police (compacte) :"
        ],
        "%1 pt": [
            "%1 pt"
        ],
        "Temperature text size in compact/panel mode": [
            "Taille du texte de température en mode compact ou panneau"
        ],
        "Show temperature in compact mode": [
            "Afficher la température en mode compact"
        ],
        "Display temperature when widget is in panel": [
            "Afficher la température lorsque le composant est dans le panneau"
        ],
        "Use bold font": [
            "Utiliser une police en gras"
        ],
        "Make temperature text bold": [
            "Afficher la température en gras"
        ],
        "Preview:": [
            "Aperçu :"
        ],
        "Compact mode preview:": [
            "Aperçu du mode compact :"
        ],
        "Hourly forecast:": [
            "Prévisions horaires :"
        ],
        "Show weather changes during the day": [
            "Afficher les changements météo au cours de la journée"
        ],
        "Forecast horizon:": [
            "Horizon des prévisions :"
        ],
        "%1 hour": [
            "%1 heure",
            "%1 heures"
        ],
        "Display interval:": [
            "Intervalle d’affichage :"
        ],
        "Every %1 hour": [
            "Toutes les heures",
            "Toutes les %1 heures"
        ],
        "Temperature:": [
            "Température :"
        ],
        "Show condition icons": [
            "Afficher les icônes des conditions"
        ],
        "Show precipitation probability": [
            "Afficher la probabilité de précipitations"
        ],
        "Daily forecast:": [
            "Prévisions quotidiennes :"
        ],
        "Show multi-day forecast": [
            "Afficher les prévisions sur plusieurs jours"
        ],
        "Number of days:": [
            "Nombre de jours :"
        ],
        "Include today": [
            "Inclure aujourd’hui"
        ],
        "Temperature range:": [
            "Plage de températures :"
        ],
        "Forecast sections appear only in the expanded and desktop views. They are disabled by default to preserve the minimal layout. Forecast data provided by Open-Meteo.": [
            "Les sections de prévisions apparaissent uniquement dans les vues étendue et du bureau. Elles sont désactivées par défaut afin de préserver une présentation minimaliste. Données de prévision fournies par Open-Meteo."
        ],
        "Desktop Widget View:": [
            "Vue du composant sur le bureau :"
        ],
        "Configure the appearance when widget is on desktop": [
            "Configurer l’apparence du composant sur le bureau"
        ],
        "Icon size:": [
            "Taille de l’icône :"
        ],
        "Weather icon size in desktop mode": [
            "Taille de l’icône météo en mode bureau"
        ],
        "Show weather icon": [
            "Afficher l’icône météo"
        ],
        "Display weather icon in desktop widget": [
            "Afficher l’icône météo dans le composant du bureau"
        ],
        "Temperature size:": [
            "Taille de la température :"
        ],
        "Temperature text size in desktop mode": [
            "Taille du texte de température en mode bureau"
        ],
        "Show temperature": [
            "Afficher la température"
        ],
        "Display temperature in desktop widget": [
            "Afficher la température dans le composant du bureau"
        ],
        "Bold temperature text": [
            "Température en gras"
        ],
        "Weather condition size:": [
            "Taille des conditions météo :"
        ],
        "Weather condition text size (e.g., 'Partly cloudy')": [
            "Taille du texte des conditions météo (par ex. « Partiellement nuageux »)"
        ],
        "Show weather condition": [
            "Afficher les conditions météo"
        ],
        "Display weather condition description": [
            "Afficher la description des conditions météo"
        ],
        "These settings apply to the desktop widget view only. For panel/compact view, use the 'Compact View' tab.": [
            "Ces paramètres s’appliquent uniquement au composant du bureau. Pour le panneau ou la vue compacte, utilisez l’onglet « Vue compacte »."
        ],
        "System": [
            "Système"
        ],
        "Language:": [
            "Langue :"
        ],
        "Location:": [
            "Emplacement :"
        ],
        "Detect automatically": [
            "Détecter automatiquement"
        ],
        "Use wttr.in IP-based location detection": [
            "Utiliser la détection d’emplacement par adresse IP de wttr.in"
        ],
        "Manual location:": [
            "Emplacement manuel :"
        ],
        "City name, ZIP code, or coordinates": [
            "Nom de ville, code postal ou coordonnées"
        ],
        "Enter city name (e.g., 'London'), ZIP code (e.g., '10001'), or coordinates (e.g., '51.5074,-0.1278')": [
            "Saisissez un nom de ville (par ex. « Londres »), un code postal (par ex. « 10001 ») ou des coordonnées (par ex. « 51.5074,-0.1278 »)"
        ],
        "Temperature unit:": [
            "Unité de température :"
        ],
        "Choose between Celsius and Fahrenheit": [
            "Choisir entre Celsius et Fahrenheit"
        ],
        "Update interval (minutes):": [
            "Intervalle de mise à jour (minutes) :"
        ],
        "How often to refresh weather data (5-120 minutes)": [
            "Fréquence d’actualisation des données météo (5 à 120 minutes)"
        ],
        "Display:": [
            "Affichage :"
        ],
        "Show widget background": [
            "Afficher l’arrière-plan du composant"
        ],
        "Show/hide the widget background panel": [
            "Afficher ou masquer le panneau d’arrière-plan du composant"
        ],
        "Use compact mode": [
            "Utiliser le mode compact"
        ],
        "Use compact view as default (recommended for panel)": [
            "Utiliser la vue compacte par défaut (recommandé pour le panneau)"
        ],
        "Weather data provided by wttr.in": [
            "Données météo fournies par wttr.in"
        ],
        "%1 · %2%": [
            "%1 · %2%"
        ],
        "Updating...": [
            "Mise à jour…"
        ],
        "Feels like %1": [
            "Ressenti %1"
        ],
        "H %1 / L %2": [
            "Max. %1 / Min. %2"
        ],
        "Update failed · Last update: %1": [
            "Échec de la mise à jour · Dernière mise à jour : %1"
        ],
        "Update failed": [
            "Échec de la mise à jour"
        ],
        "Last update: %1": [
            "Dernière mise à jour : %1"
        ],
        "Weather": [
            "Météo"
        ],
        "Current location": [
            "Emplacement actuel"
        ],
        "No location set": [
            "Aucun emplacement défini"
        ],
        "Refresh weather": [
            "Actualiser la météo"
        ],
        "Next %1 hour": [
            "Prochaine heure",
            "%1 prochaines heures"
        ],
        "%1%": [
            "%1%"
        ],
        "Forecast unavailable": [
            "Prévisions indisponibles"
        ],
        "Loading forecast...": [
            "Chargement des prévisions…"
        ],
        "%1-day forecast": [
            "Prévisions sur %1 jours"
        ],
        "%1° / %2°": [
            "%1° / %2°"
        ],
        "Today": [
            "Aujourd’hui"
        ],
        "Rain": [
            "Pluie"
        ],
        "Snow": [
            "Neige"
        ],
        "Thunder": [
            "Orage"
        ]
    },
    "es": {
        "General": [
            "General"
        ],
        "Compact View": [
            "Vista compacta"
        ],
        "Desktop View": [
            "Vista de escritorio"
        ],
        "Forecast": [
            "Pronóstico"
        ],
        "Icon style:": [
            "Estilo de iconos:"
        ],
        "Fill": [
            "Relleno"
        ],
        "Line": [
            "Contorno"
        ],
        "Choose between filled or line icons": [
            "Elige entre iconos rellenos o de contorno"
        ],
        "Icon size (compact):": [
            "Tamaño del icono (compacto):"
        ],
        "%1 px": [
            "%1 px"
        ],
        "Icon size in compact/panel mode": [
            "Tamaño del icono en modo compacto o panel"
        ],
        "Show icon in compact mode": [
            "Mostrar el icono en modo compacto"
        ],
        "Display weather icon when widget is in panel": [
            "Mostrar el icono del tiempo cuando el widget esté en el panel"
        ],
        "Temperature value:": [
            "Valor de temperatura:"
        ],
        "Actual": [
            "Real"
        ],
        "Feels like": [
            "Sensación térmica"
        ],
        "Choose which temperature is shown in compact mode": [
            "Elige la temperatura que se muestra en modo compacto"
        ],
        "Font size (compact):": [
            "Tamaño de fuente (compacto):"
        ],
        "%1 pt": [
            "%1 pt"
        ],
        "Temperature text size in compact/panel mode": [
            "Tamaño del texto de temperatura en modo compacto o panel"
        ],
        "Show temperature in compact mode": [
            "Mostrar la temperatura en modo compacto"
        ],
        "Display temperature when widget is in panel": [
            "Mostrar la temperatura cuando el widget esté en el panel"
        ],
        "Use bold font": [
            "Usar fuente en negrita"
        ],
        "Make temperature text bold": [
            "Mostrar la temperatura en negrita"
        ],
        "Preview:": [
            "Vista previa:"
        ],
        "Compact mode preview:": [
            "Vista previa del modo compacto:"
        ],
        "Hourly forecast:": [
            "Pronóstico por horas:"
        ],
        "Show weather changes during the day": [
            "Mostrar los cambios del tiempo durante el día"
        ],
        "Forecast horizon:": [
            "Horizonte del pronóstico:"
        ],
        "%1 hour": [
            "%1 hora",
            "%1 horas"
        ],
        "Display interval:": [
            "Intervalo de visualización:"
        ],
        "Every %1 hour": [
            "Cada hora",
            "Cada %1 horas"
        ],
        "Temperature:": [
            "Temperatura:"
        ],
        "Show condition icons": [
            "Mostrar iconos de condiciones"
        ],
        "Show precipitation probability": [
            "Mostrar la probabilidad de precipitación"
        ],
        "Daily forecast:": [
            "Pronóstico diario:"
        ],
        "Show multi-day forecast": [
            "Mostrar el pronóstico de varios días"
        ],
        "Number of days:": [
            "Número de días:"
        ],
        "Include today": [
            "Incluir hoy"
        ],
        "Temperature range:": [
            "Rango de temperaturas:"
        ],
        "Forecast sections appear only in the expanded and desktop views. They are disabled by default to preserve the minimal layout. Forecast data provided by Open-Meteo.": [
            "Las secciones de pronóstico solo aparecen en las vistas ampliada y de escritorio. Están desactivadas de forma predeterminada para conservar el diseño minimalista. Datos del pronóstico proporcionados por Open-Meteo."
        ],
        "Desktop Widget View:": [
            "Vista del widget en el escritorio:"
        ],
        "Configure the appearance when widget is on desktop": [
            "Configura la apariencia del widget en el escritorio"
        ],
        "Icon size:": [
            "Tamaño del icono:"
        ],
        "Weather icon size in desktop mode": [
            "Tamaño del icono del tiempo en modo escritorio"
        ],
        "Show weather icon": [
            "Mostrar el icono del tiempo"
        ],
        "Display weather icon in desktop widget": [
            "Mostrar el icono del tiempo en el widget de escritorio"
        ],
        "Temperature size:": [
            "Tamaño de la temperatura:"
        ],
        "Temperature text size in desktop mode": [
            "Tamaño del texto de temperatura en modo escritorio"
        ],
        "Show temperature": [
            "Mostrar la temperatura"
        ],
        "Display temperature in desktop widget": [
            "Mostrar la temperatura en el widget de escritorio"
        ],
        "Bold temperature text": [
            "Temperatura en negrita"
        ],
        "Weather condition size:": [
            "Tamaño de las condiciones meteorológicas:"
        ],
        "Weather condition text size (e.g., 'Partly cloudy')": [
            "Tamaño del texto de las condiciones (p. ej., «Parcialmente nublado»)"
        ],
        "Show weather condition": [
            "Mostrar las condiciones meteorológicas"
        ],
        "Display weather condition description": [
            "Mostrar la descripción de las condiciones meteorológicas"
        ],
        "These settings apply to the desktop widget view only. For panel/compact view, use the 'Compact View' tab.": [
            "Estos ajustes solo se aplican al widget de escritorio. Para el panel o la vista compacta, usa la pestaña «Vista compacta»."
        ],
        "System": [
            "Sistema"
        ],
        "Language:": [
            "Idioma:"
        ],
        "Location:": [
            "Ubicación:"
        ],
        "Detect automatically": [
            "Detectar automáticamente"
        ],
        "Use wttr.in IP-based location detection": [
            "Usar la detección de ubicación por IP de wttr.in"
        ],
        "Manual location:": [
            "Ubicación manual:"
        ],
        "City name, ZIP code, or coordinates": [
            "Nombre de ciudad, código postal o coordenadas"
        ],
        "Enter city name (e.g., 'London'), ZIP code (e.g., '10001'), or coordinates (e.g., '51.5074,-0.1278')": [
            "Introduce una ciudad (p. ej., «Londres»), un código postal (p. ej., «10001») o coordenadas (p. ej., «51.5074,-0.1278»)"
        ],
        "Temperature unit:": [
            "Unidad de temperatura:"
        ],
        "Choose between Celsius and Fahrenheit": [
            "Elige entre Celsius y Fahrenheit"
        ],
        "Update interval (minutes):": [
            "Intervalo de actualización (minutos):"
        ],
        "How often to refresh weather data (5-120 minutes)": [
            "Frecuencia de actualización de los datos (5–120 minutos)"
        ],
        "Display:": [
            "Visualización:"
        ],
        "Show widget background": [
            "Mostrar el fondo del widget"
        ],
        "Show/hide the widget background panel": [
            "Mostrar u ocultar el panel de fondo del widget"
        ],
        "Use compact mode": [
            "Usar el modo compacto"
        ],
        "Use compact view as default (recommended for panel)": [
            "Usar la vista compacta de forma predeterminada (recomendado para el panel)"
        ],
        "Weather data provided by wttr.in": [
            "Datos meteorológicos proporcionados por wttr.in"
        ],
        "%1 · %2%": [
            "%1 · %2%"
        ],
        "Updating...": [
            "Actualizando…"
        ],
        "Feels like %1": [
            "Sensación de %1"
        ],
        "H %1 / L %2": [
            "Máx. %1 / Mín. %2"
        ],
        "Update failed · Last update: %1": [
            "Error al actualizar · Última actualización: %1"
        ],
        "Update failed": [
            "Error al actualizar"
        ],
        "Last update: %1": [
            "Última actualización: %1"
        ],
        "Weather": [
            "Tiempo"
        ],
        "Current location": [
            "Ubicación actual"
        ],
        "No location set": [
            "No se ha definido una ubicación"
        ],
        "Refresh weather": [
            "Actualizar el tiempo"
        ],
        "Next %1 hour": [
            "Próxima hora",
            "Próximas %1 horas"
        ],
        "%1%": [
            "%1%"
        ],
        "Forecast unavailable": [
            "Pronóstico no disponible"
        ],
        "Loading forecast...": [
            "Cargando el pronóstico…"
        ],
        "%1-day forecast": [
            "Pronóstico de %1 días"
        ],
        "%1° / %2°": [
            "%1° / %2°"
        ],
        "Today": [
            "Hoy"
        ],
        "Rain": [
            "Lluvia"
        ],
        "Snow": [
            "Nieve"
        ],
        "Thunder": [
            "Tormenta"
        ]
    }
}

function substitute(message, args) {
    var result = message
    for (var index = 0; index < args.length; index++) {
        if (args[index] !== undefined) {
            result = result.split("%" + (index + 1)).join(args[index])
        }
    }
    return result
}

function pluralIndex(locale, count) {
    if (locale === "zh_CN") return 0
    if (locale === "uk") {
        return count % 10 === 1 && count % 100 !== 11
            ? 0
            : count % 10 >= 2 && count % 10 <= 4
                && (count % 100 < 12 || count % 100 > 14) ? 1 : 2
    }
    if (locale === "ar") {
        return count === 0 ? 0
            : count === 1 ? 1
            : count === 2 ? 2
            : count % 100 >= 3 && count % 100 <= 10 ? 3
            : count % 100 >= 11 && count % 100 <= 99 ? 4 : 5
    }
    if (locale === "fr") return count > 1 ? 1 : 0
    return count === 1 ? 0 : 1
}

function translate(locale, message, args) {
    var forms = catalogs[locale] && catalogs[locale][message]
    return substitute(forms ? forms[0] : message, args || [])
}

function translatePlural(locale, singular, plural, count) {
    var forms = catalogs[locale] && catalogs[locale][singular]
    var message = forms ? forms[pluralIndex(locale, count)]
                        : (count === 1 ? singular : plural)
    return substitute(message || plural, [count])
}
